RDKCMF-8871 Add missing SONAME to libmongoose
- Fixes the following issue:

  ERROR: rialto-git-r0 do_package_qa: QA Issue:
   /usr/bin/RialtoServerManagerSim contained in package
   rialto-servermanager requires libmongoose.so,
   but no providers found in RDEPENDS_rialto-servermanager? [file-rdeps]
  ERROR: rialto-git-r0 do_package_qa: QA run found fatal errors.
   Please consider fixing them.

  -- This avoids installing developmnet version of libmongoose.so
     library on the target filesystem.

- Packages mongoose binary into separate mongoose-bin
  sub-package to avoid installing it by default.

Signed-off-by: Damian Wrobel <dwrobel.contractor@libertyglobal.com>
Change-Id: I5184ddaf35f0d79f0f90f2e12c63d2591e485f68