RDK-33227, RDK-33225 : Upgrade to freetype 2.10.2, add brotli 1.0.7
Reason for change:
1. Freetype library needs to be built with brotli support to
decompress woff2 fonts.
brotli encoder library is not required.
2. Morty builds are failing with error
undefined reference to symbol 'BrotliDecoderVersion'
Dunfell recipe for curl does not have brotli support.
This change removes brotli support in curl for the morty recipe
Test Procedure: Details in ticket
Risks: NA

Signed-off-by: Simi Mathew <simim@tataelxsi.co.in>
(cherry picked from commit f7c9f132b6ad10f163df0e2d75790781923eab9a)
Change-Id: I4100a03e8c7d0aa90392ebccf2f6b3c292c97696