RDKCOM-3404 RDKCMF-8871 Add missing SONAME to libmongoose
- Fixes the following issue:
  ERROR: rialto-git-r0 do_package_qa: QA Issue:
   /usr/bin/RialtoServerManagerSim contained in package
   rialto-servermanager requires libmongoose.so,
   but no providers found in RDEPENDS_rialto-servermanager? [file-rdeps]
  ERROR: rialto-git-r0 do_package_qa: QA run found fatal errors.
   Please consider fixing them.
  -- This avoids installing developmnet version of libmongoose.so
     library on the target filesystem.
- Packages mongoose binary into separate mongoose-bin
  sub-package to avoid installing it by default.
Signed-off-by: Damian Wrobel <dwrobel.contractor@libertyglobal.com>

Reason for change: RDKCMF-8871 Add missing SONAME to libmongoose
Test Procedure: None.
Risks: Low.

(cherry picked from commit ee323cd9431de6568d50d435b9c138845ead2884)
Change-Id: I484475baabc5aab1a9bc830c5a07369143e97c67